"use client";

import Link from "next/link";
import { ArrowRight, BookMarked, Clock3, Flame, Headphones, MoveRight, Play, Sprout } from "lucide-react";
import { useEffect, useState } from "react";
import { lessons } from "@/lib/content";
import LessonCard from "./LessonCard";

type Progress = { lessonId: string; percent: number; updatedAt: string };

export default function HomeClient() {
  const [progress, setProgress] = useState<Progress[]>([]);
  const [wordCount, setWordCount] = useState(0);
  useEffect(() => { Promise.all([fetch("/api/progress").then(r => r.json()), fetch("/api/vocabulary").then(r => r.json())]).then(([p, words]) => { setProgress(p); setWordCount(words.length); }); }, []);
  const latest = lessons.find(l => l.id === progress[0]?.lessonId) ?? lessons[0];
  const latestPercent = progress.find(p => p.lessonId === latest.id)?.percent ?? 0;
  return <>
    <section className="paper-grid border-b border-[#dedbd1]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-[1.1fr_.9fr] md:py-24">
      <div><span className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#cfd9d3] bg-white/70 px-4 py-2 text-xs font-bold text-matcha"><Sprout size={15}/> 每天进步一点点</span><h1 className="text-4xl font-bold leading-[1.3] tracking-tight md:text-6xl">听见日语，<br/><span className="text-matcha">记住每一次</span>进步。</h1><p className="mt-6 max-w-xl text-base leading-8 text-[#68716c]">属于你自己的本地日语精听空间。逐句听、反复练、轻松记，把学习变成安静而持续的日常。</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/lesson/${latest.id}`} className="flex items-center gap-2 rounded-full bg-matcha px-6 py-3.5 font-bold text-white shadow-lg shadow-matcha/20"><Play size={18} fill="currentColor"/>继续学习</Link><Link href="/library" className="flex items-center gap-2 rounded-full border border-[#cbc9c1] bg-white px-6 py-3.5 font-bold">浏览资料库<ArrowRight size={18}/></Link></div></div>
      <div className="relative self-end rounded-[2rem] bg-[#2f453b] p-7 text-white shadow-2xl shadow-matcha/20"><div className="absolute -right-3 -top-4 text-5xl opacity-20">学</div><p className="text-xs tracking-[.18em] text-[#c6d3cc]">今日学习</p><h2 className="mt-4 text-2xl font-bold">{latest.title}</h2><p className="mt-2 text-sm text-[#c6d3cc]">{latest.subtitle}</p><div className="my-6 h-px bg-white/15"/><div className="flex items-end justify-between"><div><p className="text-xs text-[#c6d3cc]">学习进度</p><p className="mt-1 text-3xl font-bold">{latestPercent}<span className="text-base">%</span></p></div><Link href={`/lesson/${latest.id}`} className="grid h-12 w-12 place-items-center rounded-full bg-sakura"><Play size={19} fill="currentColor"/></Link></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-sakura" style={{ width: `${latestPercent}%` }}/></div></div>
    </div></section>
    <section className="mx-auto max-w-6xl px-5 py-14"><div className="mb-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-[#dedbd1] bg-white p-5"><Flame className="mb-4 text-sakura"/><p className="text-2xl font-bold">{progress.length}</p><p className="text-sm text-[#777f7b]">已开始的课程</p></div><div className="rounded-2xl border border-[#dedbd1] bg-white p-5"><BookMarked className="mb-4 text-matcha"/><p className="text-2xl font-bold">{wordCount}</p><p className="text-sm text-[#777f7b]">已收藏生词</p></div><div className="rounded-2xl border border-[#dedbd1] bg-white p-5"><Sprout className="mb-4 text-[#b28958]"/><p className="text-2xl font-bold">4</p><p className="text-sm text-[#777f7b]">可学习资料</p></div></div><div className="mb-7 flex items-end justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-sakura">RECOMMENDED</p><h2 className="mt-2 text-2xl font-bold">推荐精听</h2></div><Link href="/library" className="text-sm font-bold text-matcha">查看全部 →</Link></div><div className="grid gap-5 md:grid-cols-3">{lessons.map(l => <LessonCard key={l.id} lesson={l} progress={progress.find(p => p.lessonId === l.id)?.percent}/>)}</div><Link href="/business-japanese" className="group mt-5 block overflow-hidden rounded-[1.6rem] border border-[#dedbd1] bg-white transition hover:-translate-y-1 hover:shadow-xl hover:shadow-[#547565]/10"><div className="h-2 bg-[#547565]"/><div className="grid gap-5 p-6 md:grid-cols-[1fr_auto] md:items-center"><div><div className="mb-4 flex items-center gap-3"><span className="rounded-full bg-cream px-3 py-1 text-xs font-bold text-matcha">商务日语 · 203页</span><Headphones size={20} className="text-[#98a19d]"/></div><h3 className="text-xl font-bold">実用ビジネス日本語</h3><p className="mt-2 text-sm leading-6 text-[#777f7b]">原页对照、自然语音、假名提示、中文词义与商务词汇收藏</p></div><div className="flex items-center gap-5 text-xs text-[#777f7b]"><span className="flex items-center gap-1"><Clock3 size={14}/>整本精听</span><span className="flex items-center gap-1 font-bold text-matcha">开始精听 <MoveRight size={15} className="transition group-hover:translate-x-1"/></span></div></div></Link></section>
  </>;
}
